name: e_com_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  pinput: ^5.0.2
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  google_phone_number_hint: ^0.0.3
  firebase_messaging: ^16.0.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  http: ^1.5.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  # get: ^4.7.2
  get_storage: ^2.1.1
  permission_handler:
 # flutter_local_notifications: ^19.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  google_maps_flutter: ^2.12.3
  custom_map_markers: ^0.0.2+1
  country_code_picker: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_app.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/image/
    - assets/image/image_png/boy_gacket.jpg
    - assets/image/image_png/boy_gacket1.jpg
    - assets/image/image_png/girl_gacket.jpg
    - assets/image/image_png/
  fonts:
    - family: funnel
      fonts:
        - asset: assets/fonts/funnel.ttf
          style: italic
    - family: dynapuff
      fonts:
        - asset: assets/fonts/dynapuff.ttf
