// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApDaGpdm9JdZ357c8n23uP9qEkUQpgks8',
    appId: '1:914928348091:web:2d96a3f3a8af3290ce729e',
    messagingSenderId: '914928348091',
    projectId: 'loginlogout-50b1a',
    authDomain: 'loginlogout-50b1a.firebaseapp.com',
    storageBucket: 'loginlogout-50b1a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1LVT57k71-JySPSM9gRa1woHGv7eZAc',
    appId: '1:914928348091:android:b1b4f1a4776ed67fce729e',
    messagingSenderId: '914928348091',
    projectId: 'loginlogout-50b1a',
    storageBucket: 'loginlogout-50b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpLnjsBXmz7Mmt8_TNsm4zQXC1CrE_HL0',
    appId: '1:914928348091:ios:94d5148773c50e3bce729e',
    messagingSenderId: '914928348091',
    projectId: 'loginlogout-50b1a',
    storageBucket: 'loginlogout-50b1a.firebasestorage.app',
    iosBundleId: 'com.example.eComBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpLnjsBXmz7Mmt8_TNsm4zQXC1CrE_HL0',
    appId: '1:914928348091:ios:94d5148773c50e3bce729e',
    messagingSenderId: '914928348091',
    projectId: 'loginlogout-50b1a',
    storageBucket: 'loginlogout-50b1a.firebasestorage.app',
    iosBundleId: 'com.example.eComBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApDaGpdm9JdZ357c8n23uP9qEkUQpgks8',
    appId: '1:914928348091:web:a518ad7285ea4157ce729e',
    messagingSenderId: '914928348091',
    projectId: 'loginlogout-50b1a',
    authDomain: 'loginlogout-50b1a.firebaseapp.com',
    storageBucket: 'loginlogout-50b1a.firebasestorage.app',
  );

}